name: Push Docker Images
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Add on demand trigger

permissions:
  contents: read
  packages: write

jobs:
  order_processor:
    runs-on: ubuntu-latest
    name: Order Processor
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}       
    - name: Build the Docker image
      run: docker build ./src/ --file ./src/Keda.Samples.Dotnet.OrderProcessor/Dockerfile --tag ghcr.io/${{ github.repository }}/keda-sample-orderprocessor:latest
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}/keda-sample-orderprocessor:latest
  portal:
    runs-on: ubuntu-latest
    name: Portal
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}   
    - name: Build the Docker image
      run: docker build ./src/ --file ./src/Keda.Samples.DotNet.Web/Dockerfile --tag ghcr.io/${{ github.repository }}/keda-sample-portal:latest
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}/keda-sample-portal:latest
